### ISSUE TITLE
file@Reader.readLetterが例外を出力しない

### ISSUE THREAD

**Issue by cielavenir** [kuina/KuinInKuin#11]
raw_funcs.knによるとreadLetterはWEOFを返すようになっており,旧Kuinと仕様が異なっているように感じます.

\# 今こちらでcui.knを見直していたのですが　readLetterはWEOFを返すようになっていたほうが　都合が良かったりします^^;

**Comment by kuina** [comment]
うーん、なぜでしたっけ…。
思い出せませんが、何かがあって仕様を変えた可能性もありますね。

**Comment by cielavenir** [comment]
#25 を拝見しましたが、これを仕様とするということで確定のようですね。クローズいたします。

**Comment by kuina** [comment]
うーむ、本当はまだどっちにすべきか迷っているところがあります。
ユーザが readLetter を呼んだ時点で、データが存在することを仮定しているとも考えられますので…。

ただ file@ と違って cui@ では、ストリームにデータが残っているかを判定するC++の関数が標準で見つけられていないので、
cui@readLetter で取得してからでないと分からないのではないかと思いました。
