### ISSUE TITLE
builtin_func.knにsortDescがない

### ISSUE THREAD

**Issue by cielavenir** [kuina/KuinInKuin#17]
sortDescは削除予定なのか未実装なのか、どちらになりますでしょうか。

**Comment by kuina** [comment]
マルチプラットフォーム対応の都合上、ソート関数が "安定" であることが保証できなくなりました。
なので、sort して reverse すると sortDesc と同等になることから、sortDesc は不要と思い、削除しました。

**Comment by cielavenir** [comment]
[memo]
CE https://yukicoder.me/submissions/336912
AC https://yukicoder.me/submissions/437341
