### ISSUE TITLE
dict.forEachの引数が継承クラスを受け取らない

### ISSUE THREAD

**Issue by cielavenir** [kuina/KuinInKuin#18]
プログラム1はコンパイルできますがプログラム2はコンパイルできません。` [\src: 9, 16]関数呼び出しの引数の型が異なります。 3番目の引数で「func<(int, int, @Class): bool>」を指定すべきところに「func<(int, int, @K): bool>」が渡されました`となります。

プログラム1

```
class K()
	+var val: int
end class
var ans: @K
func main()
	do @ans :: #@K
	var dic: dict<int, int> :: #dict<int, int>
	do dic.add(1,2)
	do dic.forEach(f, @ans)
	func f(key: int, value: int, data: kuin@Class): bool
		;do data.val :+ value
		do @ans.val :+ value
		ret true
	end func
	do cui@print("\{@ans.val}\n")
end func
```

プログラム2

```
class K()
	+var val: int
end class
var ans: @K
func main()
	do @ans :: #@K
	var dic: dict<int, int> :: #dict<int, int>
	do dic.add(1,2)
	do dic.forEach(f, @ans)
	func f(key: int, value: int, data: @K): bool
		do data.val :+ value
		;do @ans.val :+ value
		ret true
	end func
	do cui@print("\{@ans.val}\n")
end func
```

**Comment by kuina** [comment]
あ…、仕様変更というか、特に仕様ではなかった旧Kuinの挙動によるものですが、
旧Kuinではオーバーライドした関数の引数などで特定のクラスを指定すべきところに、そのクラスを継承したクラスが指定できてしまっていました。
(kuin@Class を指定すべきところに、kuin@Class を継承した任意のクラスが指定できるなど。)

本来は仕様ではなかったため、KuinInKuin でちゃんとした実装にする過程で
型チェックが厳密に行われるようになり、「プログラム2」のケースは許容されなくなりました。
kuin@Class で受け取って、関数内部で @K にキャストするのが正しい想定になります。

**Comment by cielavenir** [comment]
[memo]
CE https://yukicoder.me/submissions/335409
AC https://yukicoder.me/submissions/437340
