### ISSUE TITLE
classTable_ が未定義

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#4]
http://kuina.ch/kuin/web のデフォルトのサンプルプログラム(100以下の素数を求めるプログラム)を、C++に変換したコードを C++のコンパイラでコンパイルすると、下記のエラーが発生します。
cl.exe: `error C2065: 'classTable_': 定義されていない識別子です。`
g++: `error: 'classTable_' was not declared in this scope`

これは、私が以前投稿したプルリクエスト( #1 )と関係があります。
`static int64_t classTable_[0];` を記述しないようにする修正をしましたが、
`static int64_t classTable_[1];` のようにして残しておくのが正解だったでしょうか？

**Comment by kuina** [comment]
あ、その後のわたしの変更が、classTable_の存在を仮定してしまっていました。修正します。

**Comment by kuina** [comment]
修正して、アップロードしました！

**Comment by tatt61880** [comment]
ありがとうございます！　クローズします。
