### ISSUE TITLE
意味解析で落ちるコード

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#41]
https://github.com/kuina/Kuin/issues/104 (意味解析でエラー) に掲載されているコードをコンパイルしようとすると落ちます。
(editor.exe を起動してこのコードを貼り付けると、貼り付けた瞬間に落ちます。)

まったく同じコードをここに転載します。
```
func main()
end func

func makeJsonT(data: []char): @Json
end func


class Json()
	var err: @JsonError
	
	+*func toStr(): []char
	end func
end class


class JsonError(@Json)
	+*func toStr(): []char
	end func
end class
```

**Comment by kuina** [comment]
再現しました、確認します。

**Comment by kuina** [comment]
ちょっと、全然分からないですね…><
(後日、時間をかけて調査します)

とりあえず落ちるのは阻止しました。
例外がキャッチできずに落ちていた不具合を修正しました。

**Comment by tatt61880** [comment]
参考になるかわかりませんが、私が調査して現時点でわかったことを備忘録として残しておきます。

以下に示す analyze.kn の rebuildStat 関数内の下記の行で、 item.parentItem が null なのに item.parentItem.def にアクセスとしていることになっているようです。
https://github.com/kuina/KuinInKuin/blob/2b95521132b035454fd1e964ec8b058a81b4146f/src/compiler/analyze.kn#L1357

冒頭で言及した kuina/Kuin#104 (意味解析でエラー) も、同様の箇所 (当然 analyze.kn と analyze.c で違いはありますが…)で問題が発生していたようです。
(参考: https://twitter.com/tatt61880/status/1048873646352023553?s=20 )

下記のコードはコンパイルできますが、コード中のコメントに書いているように c2 の定義位置を変更するとダメです。
```
func main()
    var c1: C1

	class C1()
	    ; var c2: C2 {ここだとダメ}
	    +*func toStr(): []char
	    end func
	    var c2: C2 {ここだとOK}
	end class

	class C2(C1)
	    +*func toStr(): []char
	    end func
	end class
end func
```

kuina/Kuin#104 (意味解析でエラー) で書かれている「メモ: super変数の解析時に親クラスの解析が完了していない模様。」というコメントの内容とも一致しているように思います。

**Comment by kuina** [comment]
なるほど… KuinInKuinは、修正が入った後のコードを参考に実装したので、
kuina/Kuin#104 と同じ対応で直る感じではない気がしています。( kuina/Kuin#104 のようなコードはKuinInKuinにもすでにありました)

toStrのsuperを解析しているときにエラーが起こっているところまでは見ましたが、
なぜ親クラスの解析が完了していないのかは落ち着いて調査する必要がありますね…。

**Comment by kuina** [comment]
本件修正しました！
クラスの意味解析の途中でまだメソッドの意味解析が行われていないのに、別のクラスの意味解析が始まってオーバーライド元のメソッドを参照してエラーになっていました。
メソッドやメンバ変数の意味解析を一通り終わらせてから、別のクラスの意味解析を行うように処理を 2 段階に分離しました。

戴いた再現コードが通ることを確認し、テストもこれまでどおり通ることを確認しました。

**Comment by tatt61880** [comment]
修正ありがとうございます！
クローズします。
