### ISSUE TITLE
cui@print で出力される文字列の文字コードが Kuin と KuinInKuin で異なります

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#44]
例えば下記のコードをコンパイルして実行したとき、
`cui@print` の出力は Kuin では UTF-8 で、 KuinInKuin では Shift_JIS になっているようです。
`file@Writer.writeStr` の出力は Kuin も KuinInKuin も UTF-8 になっているようです。
```
func main()
	do cui@print("cui@printによる出力\n")
	var f: file@Writer :: file@makeWriter("file.txt", false)
	do f.writeStr("ファイル出力\n")
end func
```

**Comment by kuina** [comment]
実は、そこの仕様を大変迷いまして、
もうどうやっても文字化けしない形にならないので以下の仮定をしました。

(コンソール出力)
* Windows の一般的な日本語環境では Shift_JIS で出さなければ大抵文字化けする
* それ以外の環境では wchar_t が揃っていなかったり char16_t の API が無かったりするので、UTF-8 で出すことが無難

と考えて、現状の KuinInKuin は以下の仕様になっています。

* Visual Studio でビルドすると、Shift_JIS でコンソール出力する。
* それ以外でビルドすると、UTF-8 でコンソール出力する。
* ファイルはデフォルトでは UTF-8 で統一し、将来的に文字コードは自由に選択できる予定。

もしより良い方法があればご教示ください…。

**Comment by tatt61880** [comment]
早速の回答ありがとうございます！
仕様ということでクローズします。

(Kuinの出力とKuinInKuinの出力が一致するか確認していて今回の差違に気付きました。
「Visual Studio以外でビルドすると、UTF-8 でコンソール出力する。」という仕様になっているということには気付いていませんでした。)
