### ISSUE TITLE
【Webブラウザ版】(1).toStrFmt("d") が null になる。 ("1"にならない。)

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#45]
[Webブラウザ上でコンパイルできるKuin](https://kuina.ch/kuin/web) で下記のコードを実行すると、 `(null)` が出力されます。
```
func main()
	do cui@print((1).toStrFmt("d"))
end func
```

現在、[Kuinの組み込みメソッド](https://kuina.ch/kuin/spec8) で toStrFmt の使用方法が確認できない状況になっています(改修作業中でしょうか？)。使用方法が間違っているということでしたらすみません。

**Comment by kuina** [comment]
>現在、Kuinの組み込みメソッド で toStrFmt の使用方法が確認できない状況になっています

「Kuinの組み込みメソッド」のページから、「Kuin API」のページに、各メソッドの説明を移したのでした…。
「Kuinの組み込みメソッド」のページにリンクを追記しましたっ。

しかし、toStrFmt の説明が確認できないのは「Kuin API」のページでもその通りで、
実装が追いついてから記載しようと予定しています。

で、実装になりますが、実はこれまで sprintf に投げていたので、JavaScript 対応するときに困ってしまいました。
おそらく sprintf 相当の関数を自前実装する必要があり、結構大変そうなので、v.2020.6.27 には間に合いませんでした。
がんばりましょうかね…><

**Comment by kuina** [comment]
また、float.toStr() メソッドも、JavaScript と C++ とで微妙に出力結果 (精度や形式など) に違いがあることが分かっています。
float.toStr() も同時に何とかしたいですね…。

**Comment by kuina** [comment]
toStrFmt を実装しました！
使い方は https://kuina.ch/kuin/api/builtin#053751411075 を参照してください。
動作確認は一通りしましたが、特に float 型のほうは仕様が複雑なので、漏れがないか不安ではあります…。

**Comment by kuina** [comment]
(あとC言語の sprintf では対応していない、2進数出力ができるようにしました。)

**Comment by tatt61880** [comment]
toStrFmt を実装と使い方の記載ありがとうございます！

toStrFmt 全体の動作を細かくチェックしたわけではありませんが、
js版で `(1).toStrFmt("d")` が期待通りに動作することを確認できたのでクローズします。

【備考】
[Webブラウザ上でコンパイルできるKuin](https://kuina.ch/kuin/web) 自体の動作はまだ修正されていないようですが、
このサイトを模倣し、 `/js/kuin_web_20200627c.js` の代わりに
 `KuinInKuin/build/deploy_web/kuin.js` ( `KuinInKuin/build/deploy_for_web.bat` で作成されるファイル) を
読み込ませることで、問題が確認ができました。

**Comment by kuina** [comment]
> 備考

手順としては合っています！
ご確認ありがとうございましたっ。
