### ISSUE TITLE
.knファイルをkuin.exeに関連付けしても開けない

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#46]
https://twitter.com/Tunetugu/status/1277474997208879104?s=20

カレントディレクトリが kuin.exe の置かれているパスであれば正常に起動するようですが、そうでない場合に起動直後に終了するようです。

\form@makeWnd の setVisible の手前までは通っているようです。
https://github.com/kuina/KuinInKuin/blob/cc6f4d8415eb3a2f319cbe17dbd5bb8519e8b1dc/src/kuin_editor/form.kn#L83-L84

**Comment by kuina** [comment]
あ… 以前は、resファイルはexeのあるディレクトリにあるものとして読み込んでいましたが、
Windows以外の環境ではexeのある位置を取得する手段が提供されていないことが多いので、
resファイルはカレントディレクトリから読み込むようにしてしまいました。

Kuin Editor に限っては、Windowsでしか動作させないため特殊対応でどうにかなりそうですが、
どうするのが良いのでしょうね。

**Comment by kuina** [comment]
https://github.com/kuina/KuinInKuin/commit/f72cab990b0f81fd627c8bb5ba7071d695a908e3
で、修正しました。
コンパイルオプションにより、カレントディレクトリを exe のディレクトリに自動設定するという、やや無理矢理な対応です。(Windows 以外、exe のディレクトリが取れない環境が多いためやむを得ず…。)
ただ、カレントディレクトリが重視されるケースは CUI 向けが多いと思いますので、GUI アプリのカレントディレクトリはどうなっていてもあまり差し支えないかなという割り切りでした。

**Comment by tatt61880** [comment]
修正ありがとうございます！
exeと異なるフォルダにあるファイルも問題なく開けることを確認しました。クローズします。
