### ISSUE TITLE
maxを利用すると、コンパイルできないC++コードが生成される。

### ISSUE THREAD

**Issue by yuki2006** [kuina/KuinInKuin#47]
```
func main()
 do cui@print("\{[2, 4, 1, 3].max()}")
end func
```

https://yukicoder.me/run/42e34debbaff1

について
コンパイルコマンド

kuincl.exe -i main.kn -o out.cpp -s /kuin/sys/ -e cpp -r -q

で行いましたが

GCCとWindowsのVC++ いずれにもコンパイルできないコードが生成されます。

ちなみに、
https://kuina.ch/kuin/web

で生成したコードも同様なようです。

なおexeファイルは問題なく実行されます。

```
out.cpp:1597:5: エラー: 'r_' declared as reference but not initialized
 1597 | TI_ r_;
      |     ^~
out.cpp:1598:16: エラー: invalid cast of an rvalue expression of type 'int' to type 'TI_' {aka 'long int&'}
 1598 | if(l_==0)return(TI_)0;
```

きっかけになったコード
https://yukicoder.me/submissions/504622

ちなみに、僕は失礼ながらkuinの構文には詳しくありません..

**Comment by kuina** [comment]
ご報告ありがとうございます、理論的には正しいコードのはずでしたが、
コンパイラに未初期化の値が使われていると判定されているようですね…。

**Comment by kuina** [comment]
Tattさんが修正してくださったので、マージしましたっ。

**Comment by yuki2006** [comment]
ありがとうございます。

おそらく直りましたのでcloseします。
