### ISSUE TITLE
forブロックの増減値に関する「予期せぬエラーです。」

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#51]
( 困ることは少ないと思いますが、念のため報告しておきます m(_ _)m )
下記の2種類のコードを kuin.exe でコンパイルすると、いずれも「予期せぬエラーです。」という表示が出ます。

----
```
func main()
	for(0, 3, 0.5)
	end for
end func
```
↑ コンパイルエラー `0x0002001D: 「for」ブロックの増減値は「int」型でなければなりません。 (\main: 2, 10)` になるコードです。
(`0x0002001D` = `%forIncreaseDecreaseValueMustBeInt`)

----
```
func main()
	var x: int :: 1
	for(0, 3, x)
	end for
end func
```
↑ コンパイルエラー `0x0002001E: 「for」ブロックの増減値はコンパイル時に定数にできる値でなければなりません。 (\main: 3, 10)` になるコードです。
(`0x0002001E` = `%forIncreaseDecreaseValueMustBeConst`)

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
修正しました！

**Comment by kuina** [comment]
すみません、追加でもう少し修正しました。
https://github.com/kuina/KuinInKuin/commit/ce87c643b51e885abd9b72b891b24029f62fb62a

**Comment by tatt61880** [comment]
ありがとうございます！
2件とも修正されていることを確認しました。
(追加の修正により `0x0002001D` のエラー時に `0x0002001E` が出なくなったことも確認しました :-) )
クローズします。
