### ISSUE TITLE
生成されたC++のコードで終了ステータスが0ではなくなるものがある（例外が起こっている？）

### ISSUE THREAD

**Issue by yuki2006** [kuina/KuinInKuin#53]
```
func main()
	var K: int :: cui@input().toInt(&)
	var arr1: []int :: [2, 3, 5, 7, 11, 13]
	var arr2: []int :: [4, 6, 8, 9, 10, 12]
	var ans: int
	for i(0, 5)
		for j(0, 5)
			if(arr1[i] * arr2[j] = K)
				do ans :+ 1
			end if
		end for
	end for
	do cui@print("\{(ans $ float / 36.0).toStrFmt(".15f")}\n")
end func

```
入力例 

```
0
```

エラーメッセージ
```
terminate called after throwing an instance of 'unsigned int'
```

実行例

https://yukicoder.me/run/75d0d1f5c0571

出典元

https://yukicoder.me/submissions/320421

**Comment by yuki2006** [comment]
ちなみに、
非 void を戻す関数内に return 文がありません

のバグも潰しておいたほうが良いことがあります。
（特にGCC で -O2 などをつけたときに return で不定の値が返る等があるようです）

**Comment by kuina** [comment]
確認しますっ。
(たぶん toStrFmt の cpp 向けが未実装の問題ですね…。)

>非 void を戻す関数内に return 文がありません

のようなコードは Kuin の仕様としては生成しない想定なので、
見つけ次第修正します。

**Comment by kuina** [comment]
https://github.com/kuina/KuinInKuin/issues/45#issuecomment-656304182
の修正により、本コードはエラーが発生しないことが確認できました。

**Comment by yuki2006** [comment]
早めの対応ありがとうございます。
確認しましたのでクローズします。
