### ISSUE TITLE
deploy_for_exe.bat の序盤で「0x00030002: 失敗。」と表示されます。

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#55]
> 0x00030003: コンパイル開始: 0秒。
> 0x00030004: 字句構文解析完了: 1.035秒。
> 0x00030005: 意味解析完了: 1.074秒。
> 0x00030002: 失敗。
> 0x00030003: コンパイル開始: 0秒。
> …

おそらく、直近の変更( 003e05da2ce4c2b791390ae3dcfa0646337ef7d4 )で修正された convert.kn を用いてコンパイルされた kuincl.exe が build/kuincl.exe にコミットされていないためだと思います。

(「失敗。」と出るものの、続きの処理が問題なさそうなのであまり気にしなくて良いかもしれませんが念のため報告しておくことにしました。 m(_ _)m )

**Comment by kuina** [comment]
あ、すみません…仰るとおり kuincl の更新忘れでした><
更新しました。

**Comment by tatt61880** [comment]
早速の対応ありがとうございます！
クローズします。
