### ISSUE TITLE
kuincl.exe の -s 省略時の挙動

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#57]
[Kuin言語仕様11 コンパイラとIDE](https://kuina.ch/kuin/spec11) には、
「省略時の挙動」として `コンパイラが存在するディレクトリ/sys/` と書かれていますが、
実際にはそうなっていないようです。

より具体的に言うと、環境変数の %PATH% に kuincl.exe の置かれているディレクトリを設定した状態で、
`kuincl.exe -i main.kn`
を実行すると
`0x00000005: ファイル「sys/exe/kuin.kn」が開けません。`
というエラーになってしまいます。

#46 と同様、 Windows 以外の環境での対応は困難かと思われますが、 
Windows環境だけでも、 -s を省略しても問題なく動作する状態にしていただけると助かります。

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
アドホックな対応では限界を感じたので、
方針を根本から見直しました。

* 「-x curtoexe」オプションはやっぱりやめました。
* resフォルダやresファイルは、Windowsではexeの位置からの相対でアクセスします。 Windows以外ではカレントディレクトリからの相対でアクセスします。(これまでは常にカレントディレクトリからの相対でした。)
* カレントディレクトリは、一般的なカレントディレクトリ以外の使い方はしないようにしました。
* cppでの出力でも、Windowsではexeの位置が取得できるようにして、exe版と同様の方針にしました。

環境変数を設定して、任意のカレントディレクトリからkuinclを使ったコンパイルや、kuinエディタを開くことが確認できました。

**Comment by tatt61880** [comment]
早速の対応ありがとうございます！
言われてみると、その方針が良いように思います。

問題が解決していることを確認できたのでクローズします。
