### ISSUE TITLE
【Web版】repeatメソッドが動作しない。

### ISSUE THREAD

**Issue by tatt61880** [kuina/KuinInKuin#59]
`「Hey!Hey!Hey!」` を出力するコードですが、Web版だと `「」` になります。
```
func main()
	do cui@print("「\{"Hey!".repeat(3)}」\n")
end func
```
----
引数が []char型でない場合は、実行時エラーになるようです。
```
func main()
	var x: []int :: [7].repeat(3)
	for i(0, 2)
		do cui@print("x[\{i}]=\{x[i]}\n")
	end for
end func
```
↑Chrome のコンソールに下記のエラーメッセージが表示されます。
`An error occurred: 0xRangeError: Invalid array length`

----
なお、toStrFmtの引数が "03d" のように0埋め指定の場合も正しい出力になりません。
toStrFmt の実装に repeat が使われているためです。
```
func main()
	do cui@print("\{(7).toStrFmt("03d")}\n")
end func
```
↑ `007` が出力されずに、 `7` が出力されます。

**Comment by kuina** [comment]
確認しますっ。

**Comment by kuina** [comment]
修正しました！
Web版コンパイラは、本家と同じリリースタイミングで、8/17頃に差し替える予定です。

**Comment by tatt61880** [comment]
早速の修正ありがとうございます！
手元の環境で問題が解消していることを確認しました。クローズします。
