### ISSUE TITLE
エディタがフリーズする

### ISSUE THREAD

**Issue by chizuko610** [kuina/KuinInKuin#60]
![ああああ](https://user-images.githubusercontent.com/46388275/111841216-fb2ee980-8940-11eb-83e9-b5c3177a7555.png)
画像で失礼いたします。
エディタがフリーズする現象を発見しましたので報告いたします。
v.2020.9.17、再現性あり

**Comment by tatt61880** [comment]
再現するコードの作成を試みました。
完全に同じ現象と言えるのか自信がないですが、下記のコードで `@D` の箇所を `@C` にしてカーソルを動かすとフリーズします。
循環参照が原因だと思います。
```
class C(@D)
end class

func main()
	var c: @C :: #@C
	do cui@print("\{c}\n")
end func
```

**Comment by kuina** [comment]
修正しました！

**Comment by tatt61880** [comment]
修正ありがとうございます！
私が投稿したコードではフリーズしなくなったことを確認しました。

**Comment by chizuko610** [comment]
> 修正しました！


修正ありがとうございます。
フリーズしなくなったことを確認しました。

**Comment by chizuko610** [comment]
> 修正しました！


修正ありがとうございます！
